[network]
listen_address = "/ip4/127.0.0.1/tcp/6885"
dial_peers = ["/ip4/127.0.0.1/tcp/6884"]
max_pending_incoming = 10
max_pending_outgoing = 10
max_established_incoming = 50
max_established_outgoing = 50
max_established_per_peer = 1
max_workbase_per_second = 10
max_userworkbase_per_second = 10
max_miningshare_per_second = 100
max_inventory_per_second = 100
max_transaction_per_second = 100
rate_limit_window_secs = 1
max_requests_per_second = 1
peer_inactivity_timeout_secs = 60
dial_timeout_secs = 30

[store]
path = "./store.1.db"
background_task_frequency_hours = 24
pplns_ttl_days = 7

[stratum]
hostname = "0.0.0.0"
port = 13333
start_difficulty = 1
minimum_difficulty = 1
solo_address = "tb1qyazxde6558qj6z3d9np5e6msmrspwpf6k0qggk"
# The bitcoin address to use for first jobs when there are no shares
bootstrap_address = "tb1qyazxde6558qj6z3d9np5e6msmrspwpf6k0qggk"
zmqpubhashblock = "tcp://127.0.0.1:28332"
# The network can be "main", "testnet4" or "signet"
network = "signet"
version_mask = "1fffe000"
# The difficulty multiplier defines the window size for calculating payout proportions
# See https://github.com/p2poolv2/p2poolv2/wiki/Difficult-Multiplier on how to choose this
difficulty_multiplier = 1.0
# Add a pool signature, if you want. Comment out the line if you want
# to mine anonymous blocks. This signature is only used to show others
# how large your pool is, if you are running private, there is no need
# to add a pool signature. Maximum length 16 bytes.
pool_signature = "P2Poolv2"

[miner]
pubkey = "020202020202020202020202020202020202020202020202020202020202020202"

[bitcoinrpc]
# RPC credentials are loaded from env vars
url = "http://127.0.0.1:38332"
username = "p2pool"
password = "p2pool"

[logging]
# For system run services you can specify a file path
# file = "/var/log/p2pool/p2pool.log"
# For container or local run it is recommended to use console output
console = false
level = "debug"

[api]
hostname = "127.0.0.1"
port = 3000
# Optional authentication credentials
# auth_user = "admin"
# auth_token is of the format salt:password-hmac. Use can p2poolv2_cli gen-auth to generate a token.
# auth_token = "your_secret_token"

